--
-- INEGI Encuesta Intercensal 2015 - Personas
--

CREATE TABLE encuesta_intercensal_2015_personas (

    id_viv                character varying,
    id_persona            character varying,
    ent                   character(2),
    nom_ent               character varying,
    mun                   character(3),
    nom_mun               character varying,
    loc50k                character(4),
    nom_loc               character varying,
    cobertura             smallint,
    estrato               character varying,
    upm                   character varying,
    factor                smallint,
    numper                smallint,
    sexo                  smallint,
    edad                  smallint,
    parent                smallint,
    parent_otro_c         smallint,
    ident_madre           smallint,
    ident_padre           smallint,
    sersalud              smallint,
    afrodes               smallint,
    acta_nac              smallint,
    dhsersal1             smallint,
    dhsersal2             smallint,
    perte_indigena        smallint,
    ent_pais_nac          smallint,
    nacionalidad          smallint,
    hlengua               smallint,
    qdialect_c            smallint,
    qdialect_inali        smallint,
    hespanol              smallint,
    elengua               smallint,
    asisten               smallint,
    mun_asi               character(3),
    nom_mun_asi           character varying,
    ent_pais_asi          character(3),
    tie_traslado_escu     smallint,
    med_traslado_esc1     smallint,
    med_traslado_esc2     smallint,
    med_traslado_esc3     smallint,
    escolari              smallint,
    nivacad               smallint,
    alfabet               smallint,
    escoacum              smallint,
    mun_res10             character(3),
    nom_mun_res10         character varying,
    ent_pais_res10        character(3),
    situa_conyugal        smallint,
    ident_pareja          smallint,
    conact                smallint,
    ocupacion_c           smallint,
    situacion_trab        smallint,
    aguinaldo             smallint,
    vacaciones            smallint,
    servicio_medico       smallint,
    utilidades            smallint,
    incap_sueldo          smallint,
    sar_afore             smallint,
    credito_vivienda      smallint,
    ingtrmen              integer,
    actividades_c         smallint,
    mun_trab              character(3),
    nom_mun_trab          character varying,
    ent_pais_trab         character(3),
    tie_traslado_trab     smallint,
    med_traslado_trab1    smallint,
    med_traslado_trab2    smallint,
    med_traslado_trab3    smallint,
    acti_sin_pago1        smallint,
    acti_sin_pago2        smallint,
    acti_sin_pago3        smallint,
    acti_sin_pago4        smallint,
    acti_sin_pago5        smallint,
    acti_sin_pago6        smallint,
    acti_sin_pago7        smallint,
    acti_sin_pago8        smallint,
    hijos_nac_vivos       smallint,
    hijos_fallecidos      smallint,
    hijos_sobreviv        smallint,
    fecha_nac_m           smallint,
    fecha_nac_a           smallint,
    sobrevivencia         smallint,
    edad_morir_d          smallint,
    edad_morir_m          smallint,
    edad_morir_a          smallint,
    tamloc                smallint

);
