--
-- INEGI Encuesta Intercensal 2015 - Viviendas
--

CREATE TABLE encuesta_intercensal_2015_viviendas (

    id_viv              character varying,
    ent                 character(2),
    nom_ent             character varying,
    mun                 character(3),
    nom_mun             character varying,
    loc50k              character(4),
    nom_loc             character varying,
    cobertura           smallint,
    estrato             character varying,
    upm                 character varying,
    factor              smallint,
    clavivp             smallint,
    paredes             smallint,
    techos              smallint,
    pisos               smallint,
    cuadorm             smallint,
    totcuart            smallint,
    cocina              smallint,
    lugar_cocina        smallint,
    combustible         smallint,
    estufa              smallint,
    electricidad        smallint,
    focos               smallint,
    focos_ahorra        smallint,
    agua_entubada       smallint,
    aba_agua_entu       smallint,
    aba_agua_no_entu    smallint,
    tinaco              smallint,
    cisterna            smallint,
    bomba_agua          smallint,
    regadera            smallint,
    boiler              smallint,
    calentador_solar    smallint,
    aire_acon           smallint,
    panel_solar         smallint,
    sersan              smallint,
    conagua             smallint,
    usoexc              smallint,
    drenaje             smallint,
    destino_basura      smallint,
    separa_basura       smallint,
    separa_ali          smallint,
    separa_abo          smallint,
    separa_ven          smallint,
    refrigerador        smallint,
    lavadora            smallint,
    horno               smallint,
    autoprop            smallint,
    radio               smallint,
    televisor           smallint,
    televisor_pp        smallint,
    computadora         smallint,
    telefono            smallint,
    celular             smallint,
    internet            smallint,
    serv_tv_paga        smallint,
    tenencia            smallint,
    num_due_viv1        smallint,
    num_due_viv2        smallint,
    escrituras_viv      smallint,
    forma_adqui         smallint,
    financiamiento      smallint,
    deuda               smallint,
    numpers             smallint,
    ingr_perotropais    smallint,
    ingr_perdentpais    smallint,
    ingr_ayugob         smallint,
    ingr_jubpen         smallint,
    terreno_agrope      smallint,
    terreno_vivero      smallint,
    num_due_terr        smallint,
    alim_adu1           smallint,
    alim_adu2           smallint,
    alim_adu3           smallint,
    ing_alim_adu1       smallint,
    ing_alim_adu2       smallint,
    ing_alim_adu3       smallint,
    alim_men1           smallint,
    alim_men2           smallint,
    alim_men3           smallint,
    ing_alim_men1       smallint,
    ing_alim_men2       smallint,
    ing_alim_men3       smallint,
    tamloc              smallint,
    tipohog             smallint,
    jefe_sexo           smallint,
    jefe_edad           smallint,
    ingtrhog            integer

);
